export interface BluffTopic {
  id: string;
  category: string;
  text: string;
  hint?: string;
  source?: 'curated' | 'generated';
}

interface TopicTemplateOption {
  id: string;
  label: string;
}

interface TopicTemplate {
  id: string;
  category: string;
  hint: string;
  text: string;
  options: TopicTemplateOption[];
}

/*
 * Hand-written topics stay available as a curated base.
 */
export const CURATED_TOPICS: BluffTopic[] = [

  {
    id: 'late_class',
    category: 'Campus Life',
    text: 'Reason bakit late sa class',
    hint: 'Something connected to everyday campus life.',
  },
  {
    id: 'petsa_de_peligro',
    category: 'Student Life',
    text: 'Food na binibili kapag petsa de peligro',
    hint: 'Think about a common student experience.',
  },
  {
    id: 'assignment_excuse',
    category: 'Student Life',
    text: 'Excuse kapag hindi nakagawa ng assignment',
    hint: 'Think about a common student experience.',
  },
  {
    id: 'campus_tambay',
    category: 'Campus Life',
    text: 'Lugar na magandang tambayan between classes',
    hint: 'Something connected to everyday campus life.',
  },
  {
    id: 'crush_sign',
    category: 'Love & Connections',
    text: 'Sign na baka may crush sa iyo ang isang tao',
    hint: 'Something about interactions, feelings, or connections.',
  },
  {
    id: 'baguio_weather',
    category: 'Baguio',
    text: 'Bagay na laging dala dahil sa Baguio weather',
    hint: 'Think about everyday life in Baguio.',
  },
  {
    id: 'exam_survival',
    category: 'Academics',
    text: 'Ginagawa para makasurvive sa exam week',
    hint: 'Something related to classes, studying, or schoolwork.',
  },
  {
    id: 'groupwork',
    category: 'Academics',
    text: 'Pinaka-common na problema sa group work',
    hint: 'Something related to classes, studying, or schoolwork.',
  },
  {
    id: 'vacant',
    category: 'Campus Life',
    text: 'Ginagawa kapag mahaba ang vacant',
    hint: 'Something connected to everyday campus life.',
  },
  {
    id: 'morning_class',
    category: 'Student Life',
    text: 'Unang naiisip kapag may 7:30 AM class',
    hint: 'Think about a common student experience.',
  },
  {
    id: 'canteen_order',
    category: 'Food',
    text: 'Safe order kapag hindi mo alam ang kakainin',
    hint: 'Something involving food or drinks.',
  },
  {
    id: 'review_place',
    category: 'Academics',
    text: 'Best type of place para mag-review',
    hint: 'Something related to classes, studying, or schoolwork.',
  },
  {
    id: 'rain',
    category: 'Baguio',
    text: 'Problem kapag biglang umulan',
    hint: 'Think about everyday life in Baguio.',
  },
  {
    id: 'presentation',
    category: 'Academics',
    text: 'Kinakabahan ka rito bago ang presentation',
    hint: 'Something related to classes, studying, or schoolwork.',
  },
  {
    id: 'college_expense',
    category: 'Student Life',
    text: 'Unexpected college expense',
    hint: 'Think about a common student experience.',
  },
  {
    id: 'sleepy_class',
    category: 'Student Life',
    text: 'Ginagawa kapag inaantok sa class',
    hint: 'Think about a common student experience.',
  },
  {
    id: 'chat_reply',
    category: 'Love & Connections',
    text: 'Reason kung bakit matagal mag-reply',
    hint: 'Something about interactions, feelings, or connections.',
  },
  {
    id: 'weekend',
    category: 'Random',
    text: 'Ideal way to spend a free weekend',
    hint: 'An everyday situation or habit.',
  },
  {
    id: 'coffee',
    category: 'Food',
    text: 'Reason kung bakit bumibili ng coffee',
    hint: 'Something involving food or drinks.',
  },
  {
    id: 'deadline',
    category: 'Academics',
    text: 'Reaction kapag na-move ang deadline',
    hint: 'Something related to classes, studying, or schoolwork.',
  },
  {
    id: 'commute',
    category: 'Baguio',
    text: 'Pinaka-stressful part ng commute',
    hint: 'Think about everyday life in Baguio.',
  },
  {
    id: 'freshie',
    category: 'Campus Life',
    text: 'Advice na ibibigay mo sa freshie',
    hint: 'Something connected to everyday campus life.',
  },
  {
    id: 'low_battery',
    category: 'Random',
    text: 'Ginagawa kapag 5% na lang ang battery',
    hint: 'An everyday situation or habit.',
  },
  {
    id: 'study_music',
    category: 'Random',
    text: 'Pinapakinggan habang nag-aaral',
    hint: 'An everyday situation or habit.',
  },
  {
    id: 'free_food',
    category: 'Food',
    text: 'Reaction kapag may libreng pagkain',
    hint: 'Something involving food or drinks.',
  },
  {
    id: 'prof_absent',
    category: 'Campus Life',
    text: 'Reaction kapag absent ang prof',
    hint: 'Something connected to everyday campus life.',
  },
  {
    id: 'recitation',
    category: 'Academics',
    text: 'Ginagawa kapag feeling mo tatawagin ka sa recitation',
    hint: 'Something related to classes, studying, or schoolwork.',
  },
  {
    id: 'friend_cancel',
    category: 'Random',
    text: 'Reason kung bakit kino-cancel ang lakad',
    hint: 'An everyday situation or habit.',
  },
  {
    id: 'bad_wifi',
    category: 'Student Life',
    text: 'Ginagawa kapag mahina ang Wi-Fi',
    hint: 'Think about a common student experience.',
  },
  {
    id: 'after_exam',
    category: 'Academics',
    text: 'Unang gagawin pagkatapos ng last exam',
    hint: 'Something related to classes, studying, or schoolwork.',
  },
].map((topic) => ({
  ...topic,
  source: 'curated' as const,
}));

/*
 * Controlled generation:
 * Every template has its own approved option list.
 * We NEVER mix arbitrary places/situations from unrelated pools,
 * so prompts stay coherent.
 *
 * Each template only has one variable: {value}.
 */
export const TOPIC_TEMPLATES: TopicTemplate[] = [
  {
    id: "campus_free_time",
    category: "Campus Life",
    hint: "Something connected to how students spend time on campus.",
    text: "Best thing to do during {value}",
    options: [
      { id: "long_vacant", label: "a long vacant" },
      { id: "short_break", label: "a short break between classes" },
      { id: "waiting_next", label: "waiting for your next class" },
      { id: "after_dismissal", label: "time after dismissal" },
      { id: "before_first", label: "the time before your first class" },
      { id: "lunch_break", label: "lunch break" },
      { id: "waiting_friends", label: "waiting for your friends" },
      { id: "early_arrival", label: "arriving on campus too early" },
      { id: "free_hour", label: "an unexpected free hour" },
      { id: "class_cancelled", label: "a suddenly cancelled class" },
    ],
  },
  {
    id: "campus_awkward",
    category: "Campus Life",
    hint: "Think about an awkward campus moment.",
    text: "Most awkward thing that can happen during {value}",
    options: [
      { id: "orientation", label: "orientation" },
      { id: "org_event", label: "an org event" },
      { id: "campus_tour", label: "a campus tour" },
      { id: "enrollment_line", label: "an enrollment line" },
      { id: "school_program", label: "a school program" },
      { id: "club_recruitment", label: "club recruitment" },
      { id: "class_intro", label: "first-day introductions" },
      { id: "campus_event", label: "a campus event" },
      { id: "group_meeting", label: "a group meeting" },
      { id: "student_activity", label: "a student activity" },
    ],
  },
  {
    id: "campus_go_to",
    category: "Campus Life",
    hint: "Think about common reasons students move around campus.",
    text: "Most likely reason you would go to {value}",
    options: [
      { id: "library", label: "the library" },
      { id: "canteen", label: "the canteen" },
      { id: "student_lounge", label: "a student lounge" },
      { id: "registrar", label: "the registrar" },
      { id: "chapel", label: "the chapel" },
      { id: "gym", label: "the gym" },
      { id: "computer_lab", label: "a computer lab" },
      { id: "campus_ground", label: "the campus grounds" },
      { id: "office", label: "a school office" },
      { id: "study_area", label: "a study area" },
    ],
  },
  {
    id: "campus_waiting",
    category: "Campus Life",
    hint: "Something students do while waiting around campus.",
    text: "Thing you would probably do while waiting at {value}",
    options: [
      { id: "library", label: "the library" },
      { id: "canteen", label: "the canteen" },
      { id: "hallway", label: "the hallway" },
      { id: "lobby", label: "a campus lobby" },
      { id: "waiting_area", label: "a waiting area" },
      { id: "study_area", label: "a study area" },
      { id: "campus_gate", label: "the campus gate" },
      { id: "outside_class", label: "outside a classroom" },
      { id: "covered_walkway", label: "a covered walkway" },
      { id: "student_lounge", label: "a student lounge" },
    ],
  },
  {
    id: "campus_item",
    category: "Campus Life",
    hint: "Think about something useful for a normal school day.",
    text: "Most useful thing to have during {value}",
    options: [
      { id: "whole_day", label: "whole-day classes" },
      { id: "enrollment", label: "enrollment day" },
      { id: "org_activity", label: "an org activity" },
      { id: "long_vacant", label: "a long vacant" },
      { id: "campus_event", label: "a campus event" },
      { id: "busy_day", label: "a very busy school day" },
      { id: "first_day", label: "the first day of classes" },
      { id: "rainy_school", label: "a rainy school day" },
      { id: "exam_day", label: "an exam day" },
      { id: "presentation_day", label: "a presentation day" },
    ],
  },
  {
    id: "campus_sound",
    category: "Campus Life",
    hint: "Think about familiar things you hear around school.",
    text: "Something you would not be surprised to hear near {value}",
    options: [
      { id: "canteen", label: "the canteen" },
      { id: "hallway", label: "a busy hallway" },
      { id: "library", label: "the library entrance" },
      { id: "campus_gate", label: "the campus gate" },
      { id: "classroom", label: "a classroom before class" },
      { id: "student_lounge", label: "a student lounge" },
      { id: "gym", label: "the gym" },
      { id: "computer_lab", label: "a computer lab" },
      { id: "event_area", label: "a campus event area" },
      { id: "waiting_area", label: "a waiting area" },
    ],
  },
  {
    id: "student_first_move",
    category: "Student Life",
    hint: "Think about a relatable student situation.",
    text: "Unang ginagawa kapag {value}",
    options: [
      { id: "late_woke", label: "late kang nagising" },
      { id: "low_allowance", label: "konti na lang allowance mo" },
      { id: "forgot_charger", label: "naiwan mo charger mo" },
      { id: "forgot_umbrella", label: "wala kang dalang payong" },
      { id: "no_sleep", label: "kulang ka sa tulog" },
      { id: "long_day", label: "mahaba pa ang school day" },
      { id: "hungry", label: "gutom ka before class" },
      { id: "battery_low", label: "lowbat ka na" },
      { id: "missed_ride", label: "naiwan ka ng jeep or bus" },
      { id: "forgot_id", label: "nakalimutan mo school ID mo" },
    ],
  },
  {
    id: "student_reaction",
    category: "Student Life",
    hint: "Think about a common reaction students have.",
    text: "Pinaka-relatable na reaction kapag {value}",
    options: [
      { id: "no_class", label: "walang pasok" },
      { id: "early_dismissal", label: "maagang dismissal" },
      { id: "surprise_expense", label: "may unexpected expense" },
      { id: "allowance_arrives", label: "dumating na allowance" },
      { id: "free_period", label: "nagkaroon ng free period" },
      { id: "wifi_returns", label: "bumalik ang Wi-Fi" },
      { id: "deadline_extended", label: "na-extend ang deadline" },
      { id: "class_moved", label: "na-move ang class" },
      { id: "friend_absent", label: "absent ang kaibigan mo" },
      { id: "week_done", label: "tapos na ang last class of the week" },
    ],
  },
  {
    id: "student_survive",
    category: "Student Life",
    hint: "Think about everyday college survival.",
    text: "Best way to survive {value}",
    options: [
      { id: "730", label: "a 7:30 AM class" },
      { id: "whole_day", label: "whole-day classes" },
      { id: "exam_week", label: "exam week" },
      { id: "little_sleep", label: "a day with very little sleep" },
      { id: "tight_budget", label: "a tight weekly budget" },
      { id: "long_commute", label: "a long commute" },
      { id: "many_deadlines", label: "multiple deadlines" },
      { id: "rainy_week", label: "a rainy school week" },
      { id: "back_to_back", label: "back-to-back classes" },
      { id: "busy_month", label: "a very busy month" },
    ],
  },
  {
    id: "student_phone",
    category: "Student Life",
    hint: "Think about why a student might check their phone.",
    text: "Most likely reason to check your phone during {value}",
    options: [
      { id: "class_break", label: "a class break" },
      { id: "commute", label: "your commute" },
      { id: "study_session", label: "a study session" },
      { id: "long_vacant", label: "a long vacant" },
      { id: "lunch", label: "lunch" },
      { id: "waiting_prof", label: "waiting for the professor" },
      { id: "group_meeting", label: "a group meeting" },
      { id: "event", label: "a campus event" },
      { id: "review", label: "review time" },
      { id: "line", label: "a long line" },
    ],
  },
  {
    id: "student_forget",
    category: "Student Life",
    hint: "Think about things students regret forgetting.",
    text: "Thing you would regret forgetting on {value}",
    options: [
      { id: "exam_day", label: "exam day" },
      { id: "rainy_day", label: "a rainy day" },
      { id: "presentation_day", label: "presentation day" },
      { id: "long_day", label: "a whole-day schedule" },
      { id: "lab_day", label: "lab day" },
      { id: "enrollment_day", label: "enrollment day" },
      { id: "field_activity", label: "a field activity" },
      { id: "org_day", label: "an org event day" },
      { id: "commute_day", label: "a long commute day" },
      { id: "first_day", label: "the first day of class" },
    ],
  },
  {
    id: "student_borrow",
    category: "Student Life",
    hint: "Think about something a student might need from a friend.",
    text: "Most likely thing you would borrow when {value}",
    options: [
      { id: "forgot_pen", label: "you forgot your pen" },
      { id: "battery_low", label: "your battery is low" },
      { id: "rain", label: "it suddenly rains" },
      { id: "forgot_notes", label: "you forgot your notes" },
      { id: "cold", label: "it gets really cold" },
      { id: "calculator", label: "you forgot your calculator" },
      { id: "paper", label: "you run out of paper" },
      { id: "data", label: "you have no mobile data" },
      { id: "hair_mess", label: "you need to fix yourself quickly" },
      { id: "hungry", label: "you are unexpectedly hungry" },
    ],
  },
  {
    id: "academic_stress",
    category: "Academics",
    hint: "Something related to schoolwork or assessments.",
    text: "Pinaka-stressful na part ng {value}",
    options: [
      { id: "exam", label: "an exam" },
      { id: "quiz", label: "a quiz" },
      { id: "group_project", label: "a group project" },
      { id: "presentation", label: "a presentation" },
      { id: "recitation", label: "recitation" },
      { id: "lab", label: "a lab activity" },
      { id: "research", label: "research" },
      { id: "coding_project", label: "a coding project" },
      { id: "report", label: "a written report" },
      { id: "final_project", label: "a final project" },
    ],
  },
  {
    id: "academic_before",
    category: "Academics",
    hint: "Think about what students do right before an academic task.",
    text: "Ginagawa mo right before {value}",
    options: [
      { id: "exam", label: "an exam" },
      { id: "quiz", label: "a quiz" },
      { id: "recitation", label: "recitation" },
      { id: "presentation", label: "a presentation" },
      { id: "demo", label: "a project demo" },
      { id: "defense", label: "a defense" },
      { id: "lab", label: "a lab activity" },
      { id: "submission", label: "a major submission" },
      { id: "reporting", label: "class reporting" },
      { id: "consultation", label: "a consultation" },
    ],
  },
  {
    id: "academic_forget",
    category: "Academics",
    hint: "Think about a school item or requirement.",
    text: "Best excuse kapag nakalimutan mo ang {value}",
    options: [
      { id: "id", label: "school ID" },
      { id: "assignment", label: "assignment" },
      { id: "notebook", label: "notebook" },
      { id: "calculator", label: "calculator" },
      { id: "printed_output", label: "printed output" },
      { id: "charger", label: "laptop charger" },
      { id: "flashdrive", label: "flash drive" },
      { id: "lab_material", label: "lab material" },
      { id: "project_file", label: "project file" },
      { id: "reference", label: "reference material" },
    ],
  },
  {
    id: "academic_useful",
    category: "Academics",
    hint: "Think about something useful while doing schoolwork.",
    text: "Most useful thing during {value}",
    options: [
      { id: "review", label: "a review session" },
      { id: "exam_week", label: "exam week" },
      { id: "group_project", label: "a group project" },
      { id: "coding", label: "a coding session" },
      { id: "research", label: "research work" },
      { id: "presentation_prep", label: "presentation prep" },
      { id: "lab", label: "a lab activity" },
      { id: "writing", label: "writing a paper" },
      { id: "cramming", label: "cramming" },
      { id: "study_group", label: "a study group" },
    ],
  },
  {
    id: "academic_hear",
    category: "Academics",
    hint: "Think about something students do not want to hear.",
    text: "Pinaka-ayaw mong marinig before {value}",
    options: [
      { id: "exam", label: "an exam" },
      { id: "quiz", label: "a quiz" },
      { id: "presentation", label: "a presentation" },
      { id: "recitation", label: "recitation" },
      { id: "deadline", label: "a deadline" },
      { id: "demo", label: "a project demo" },
      { id: "defense", label: "a defense" },
      { id: "lab", label: "a lab activity" },
      { id: "submission", label: "a major submission" },
      { id: "reporting", label: "class reporting" },
    ],
  },
  {
    id: "academic_event_reaction",
    category: "Academics",
    hint: "Think about a typical classroom announcement.",
    text: "Reaction kapag {value}",
    options: [
      { id: "surprise_quiz", label: "nag-announce ng surprise quiz" },
      { id: "extension", label: "na-extend ang deadline" },
      { id: "grouping", label: "sinabing group activity" },
      { id: "open_notes", label: "sinabing open notes" },
      { id: "cancelled_exam", label: "na-postpone ang exam" },
      { id: "extra_task", label: "may additional task" },
      { id: "early_submit", label: "pinapa-submit earlier than expected" },
      { id: "free_time", label: "binigyan ng free time" },
      { id: "bonus", label: "may bonus points" },
      { id: "no_recitation", label: "walang recitation today" },
    ],
  },
  {
    id: "academic_distract",
    category: "Academics",
    hint: "Think about common distractions while studying.",
    text: "What usually distracts you while {value}",
    options: [
      { id: "reviewing", label: "reviewing" },
      { id: "coding", label: "coding" },
      { id: "reading", label: "reading notes" },
      { id: "writing", label: "writing a paper" },
      { id: "researching", label: "doing research" },
      { id: "memorizing", label: "memorizing" },
      { id: "solving", label: "solving problems" },
      { id: "groupwork", label: "doing group work" },
      { id: "watching_lecture", label: "watching a lecture" },
      { id: "making_slides", label: "making presentation slides" },
    ],
  },
  {
    id: "academic_satisfying",
    category: "Academics",
    hint: "Think about a satisfying academic moment.",
    text: "Most satisfying thing after {value}",
    options: [
      { id: "exam", label: "finishing an exam" },
      { id: "project", label: "submitting a project" },
      { id: "presentation", label: "finishing a presentation" },
      { id: "defense", label: "surviving a defense" },
      { id: "lab", label: "finishing a lab" },
      { id: "research", label: "finishing research work" },
      { id: "quiz", label: "finishing a difficult quiz" },
      { id: "coding", label: "fixing a coding task" },
      { id: "report", label: "submitting a report" },
      { id: "week", label: "finishing a heavy school week" },
    ],
  },
  {
    id: "baguio_bring",
    category: "Baguio",
    hint: "Think about Baguio weather and daily life.",
    text: "Best thing to bring kapag {value}",
    options: [
      { id: "sudden_rain", label: "biglang umulan" },
      { id: "cold_morning", label: "sobrang lamig sa umaga" },
      { id: "foggy", label: "foggy ang paligid" },
      { id: "rainy_commute", label: "umuulan habang nagko-commute" },
      { id: "weather_changes", label: "paiba-iba ang weather" },
      { id: "cold_evening", label: "malamig sa gabi" },
      { id: "walking_day", label: "marami kang lalakarin" },
      { id: "wet_day", label: "mukhang buong araw uulan" },
      { id: "windy", label: "mahangin" },
      { id: "sun_then_rain", label: "maaraw tapos biglang umulan" },
    ],
  },
  {
    id: "baguio_hassle",
    category: "Baguio",
    hint: "Think about common Baguio inconveniences.",
    text: "Pinaka-hassle na part ng {value}",
    options: [
      { id: "rush_hour", label: "Baguio rush hour" },
      { id: "rainy_day", label: "a rainy day in Baguio" },
      { id: "uphill", label: "an uphill walk" },
      { id: "fog", label: "a very foggy day" },
      { id: "cold_morning", label: "a cold morning" },
      { id: "weekend_traffic", label: "weekend traffic" },
      { id: "waiting_ride", label: "waiting for a ride" },
      { id: "wet_shoes", label: "walking with wet shoes" },
      { id: "crowded_town", label: "a crowded day in town" },
      { id: "weather_shift", label: "a sudden weather change" },
    ],
  },
  {
    id: "baguio_first_thought",
    category: "Baguio",
    hint: "Think about everyday reactions to Baguio conditions.",
    text: "First thought when {value}",
    options: [
      { id: "thick_fog", label: "the fog gets really thick" },
      { id: "sudden_rain", label: "it suddenly starts raining" },
      { id: "traffic", label: "traffic stops moving" },
      { id: "very_cold", label: "it gets unusually cold" },
      { id: "sunny", label: "the sun finally comes out" },
      { id: "crowded", label: "town gets extremely crowded" },
      { id: "no_ride", label: "you cannot find a ride" },
      { id: "wet", label: "your shoes get soaked" },
      { id: "wind", label: "the wind gets strong" },
      { id: "clear_view", label: "the weather suddenly clears" },
    ],
  },
  {
    id: "baguio_need",
    category: "Baguio",
    hint: "Think about what helps during Baguio conditions.",
    text: "Something you immediately look for when {value}",
    options: [
      { id: "rain", label: "it starts raining" },
      { id: "cold", label: "it gets cold" },
      { id: "hungry_town", label: "you get hungry in town" },
      { id: "low_battery", label: "your battery gets low while outside" },
      { id: "no_ride", label: "you cannot find a ride" },
      { id: "fog", label: "the fog gets thick" },
      { id: "wet", label: "you get wet" },
      { id: "waiting", label: "you have to wait a long time" },
      { id: "walking", label: "you still have a long walk" },
      { id: "late", label: "you realize you are running late" },
    ],
  },
  {
    id: "baguio_vibe",
    category: "Baguio",
    hint: "Think about a place or activity that fits Baguio weather.",
    text: "Best kind of place to be when {value}",
    options: [
      { id: "cold", label: "it is really cold" },
      { id: "rain", label: "it is raining" },
      { id: "foggy", label: "it is foggy" },
      { id: "sunny", label: "the weather is unusually sunny" },
      { id: "free_afternoon", label: "you have a free afternoon" },
      { id: "long_vacant", label: "you have a long vacant" },
      { id: "evening", label: "it is a cold evening" },
      { id: "weekend", label: "you have a free weekend" },
      { id: "drizzle", label: "there is light drizzle" },
      { id: "after_rain", label: "the rain just stopped" },
    ],
  },
  {
    id: "food_best",
    category: "Food",
    hint: "Something involving food or drinks.",
    text: "Best thing to eat kapag {value}",
    options: [
      { id: "low_budget", label: "low budget ka" },
      { id: "cold_weather", label: "malamig ang weather" },
      { id: "late_study", label: "late-night study session" },
      { id: "after_exam", label: "katapos ng exam" },
      { id: "long_day", label: "mahaba ang school day" },
      { id: "rainy", label: "umuulan" },
      { id: "hungry_break", label: "gutom during break" },
      { id: "cramming", label: "nagka-cram" },
      { id: "celebration", label: "may small celebration" },
      { id: "quick_meal", label: "konti lang time kumain" },
    ],
  },
  {
    id: "food_safe_order",
    category: "Food",
    hint: "Think about choosing food or drinks.",
    text: "Pinaka-safe order kapag {value}",
    options: [
      { id: "first_cafe", label: "first time mo sa cafe" },
      { id: "cant_decide", label: "hindi ka makapili" },
      { id: "new_place", label: "bago sa iyo yung place" },
      { id: "small_budget", label: "limited budget" },
      { id: "quick_break", label: "short lang ang break" },
      { id: "with_friends", label: "kasama mo barkada" },
      { id: "cold_day", label: "malamig ang araw" },
      { id: "need_energy", label: "kailangan mo ng energy" },
      { id: "not_hungry", label: "hindi ka sobrang gutom" },
      { id: "very_hungry", label: "sobrang gutom ka" },
    ],
  },
  {
    id: "food_buy_reason",
    category: "Food",
    hint: "Think about why students buy a particular food or drink.",
    text: "Most likely reason you would buy {value}",
    options: [
      { id: "coffee", label: "coffee" },
      { id: "fries", label: "fries" },
      { id: "rice_meal", label: "a rice meal" },
      { id: "milk_tea", label: "milk tea" },
      { id: "bread", label: "bread" },
      { id: "instant_noodles", label: "instant noodles" },
      { id: "snack", label: "a quick snack" },
      { id: "hot_drink", label: "a hot drink" },
      { id: "dessert", label: "dessert" },
      { id: "bottled_water", label: "bottled water" },
    ],
  },
  {
    id: "food_crave",
    category: "Food",
    hint: "Think about food cravings after a situation.",
    text: "Food you would probably crave after {value}",
    options: [
      { id: "exam", label: "a difficult exam" },
      { id: "presentation", label: "a stressful presentation" },
      { id: "long_class", label: "a long class" },
      { id: "commute", label: "a long commute" },
      { id: "rain", label: "walking in the rain" },
      { id: "coding", label: "a long coding session" },
      { id: "groupwork", label: "a tiring group meeting" },
      { id: "whole_day", label: "whole-day classes" },
      { id: "event", label: "a campus event" },
      { id: "deadline", label: "submitting a big requirement" },
    ],
  },
  {
    id: "food_priority",
    category: "Food",
    hint: "Think about what matters when choosing something to eat or drink.",
    text: "Most important thing when choosing {value}",
    options: [
      { id: "canteen_meal", label: "a canteen meal" },
      { id: "coffee", label: "coffee" },
      { id: "snack", label: "a snack" },
      { id: "lunch", label: "lunch" },
      { id: "takeout", label: "takeout" },
      { id: "breakfast", label: "breakfast before class" },
      { id: "study_food", label: "study food" },
      { id: "rainy_food", label: "food on a rainy day" },
      { id: "cheap_meal", label: "a budget meal" },
      { id: "group_order", label: "a group order" },
    ],
  },
  {
    id: "love_sign",
    category: "Love & Connections",
    hint: "Something about crushes, feelings, or social cues.",
    text: "Most obvious sign when {value}",
    options: [
      { id: "crush_classmate", label: "someone has a crush on a classmate" },
      { id: "likes_you", label: "someone might like you" },
      { id: "nervous", label: "someone gets nervous around their crush" },
      { id: "interested", label: "someone is interested in getting to know you" },
      { id: "misses_you", label: "someone misses talking to you" },
      { id: "jealous", label: "someone is a little jealous" },
      { id: "trying_talk", label: "someone is trying to start a conversation" },
      { id: "wants_attention", label: "someone wants your attention" },
      { id: "shy", label: "someone is too shy to say what they feel" },
      { id: "comfortable", label: "someone is becoming comfortable with you" },
    ],
  },
  {
    id: "love_reply",
    category: "Love & Connections",
    hint: "Think about messaging someone you like or care about.",
    text: "Best reply when {value}",
    options: [
      { id: "crush_hi", label: "your crush suddenly says hi" },
      { id: "compliment", label: "someone gives you a compliment" },
      { id: "late_reply", label: "someone apologizes for replying late" },
      { id: "invite", label: "someone asks you to hang out" },
      { id: "goodluck", label: "someone tells you good luck" },
      { id: "miss_you", label: "someone says they miss talking to you" },
      { id: "story_reply", label: "your crush replies to your story" },
      { id: "random_message", label: "someone messages you out of nowhere" },
      { id: "thank_you", label: "someone sends a sweet thank-you" },
      { id: "check_in", label: "someone checks if you are okay" },
    ],
  },
  {
    id: "love_awkward",
    category: "Love & Connections",
    hint: "Think about an awkward crush or social moment.",
    text: "Most awkward thing when {value}",
    options: [
      { id: "run_into_crush", label: "you unexpectedly run into your crush" },
      { id: "sit_beside", label: "you end up sitting beside your crush" },
      { id: "friends_tease", label: "your friends start teasing you" },
      { id: "eye_contact", label: "you make eye contact for too long" },
      { id: "chat_silence", label: "the chat suddenly goes quiet" },
      { id: "wrong_send", label: "you almost send a message to the wrong person" },
      { id: "meet_friends", label: "you meet their friends" },
      { id: "compliment", label: "they suddenly compliment you" },
      { id: "same_group", label: "you get put in the same group" },
      { id: "walk_together", label: "you unexpectedly walk together" },
    ],
  },
  {
    id: "love_reason",
    category: "Love & Connections",
    hint: "Think about reasons behind online or social behavior.",
    text: "Most likely reason someone would suddenly {value}",
    options: [
      { id: "reply_late", label: "reply late" },
      { id: "react_story", label: "react to your story" },
      { id: "message_again", label: "message you again" },
      { id: "go_quiet", label: "become quiet" },
      { id: "delete_message", label: "delete a message" },
      { id: "like_old_post", label: "like an older post" },
      { id: "ask_question", label: "ask a random question" },
      { id: "send_meme", label: "send you a meme" },
      { id: "check_in", label: "check in on you" },
      { id: "avoid_eye", label: "avoid eye contact" },
    ],
  },
  {
    id: "love_notice",
    category: "Love & Connections",
    hint: "Think about first impressions and getting to know someone.",
    text: "What you notice first when {value}",
    options: [
      { id: "meet_new", label: "you meet someone new" },
      { id: "crush_walks", label: "your crush walks into the room" },
      { id: "talk_first", label: "you talk to someone for the first time" },
      { id: "groupmate", label: "you get a new groupmate" },
      { id: "classmate", label: "you notice a new classmate" },
      { id: "hangout", label: "you hang out with someone one-on-one" },
      { id: "video_call", label: "you join a video call" },
      { id: "event_meet", label: "you meet someone at an event" },
      { id: "friend_intro", label: "a friend introduces someone" },
      { id: "study_together", label: "you study with someone new" },
    ],
  },
  {
    id: "barkada_reason",
    category: "Barkada",
    hint: "Think about common friend-group situations.",
    text: "Pinaka-common na dahilan bakit {value}",
    options: [
      { id: "plan_cancel", label: "naca-cancel ang barkada plan" },
      { id: "friend_late", label: "late ang isang friend" },
      { id: "gc_quiet", label: "biglang tahimik ang GC" },
      { id: "plan_change", label: "nabago ang original plan" },
      { id: "someone_leave", label: "may umuwing maaga" },
      { id: "budget_change", label: "nagbago ang budget" },
      { id: "meet_delay", label: "na-delay ang meetup" },
      { id: "food_change", label: "nagpalit ng kakainan" },
      { id: "study_fail", label: "hindi natuloy ang study session" },
      { id: "picture_many", label: "ang tagal bago matapos mag-picture" },
    ],
  },
  {
    id: "barkada_chaos",
    category: "Barkada",
    hint: "Think about the chaotic part of hanging out with friends.",
    text: "Most chaotic part of {value}",
    options: [
      { id: "outing", label: "a barkada outing" },
      { id: "group_lunch", label: "a group lunch" },
      { id: "study_session", label: "a barkada study session" },
      { id: "roadtrip", label: "a road trip" },
      { id: "movie", label: "a movie plan" },
      { id: "birthday", label: "a birthday celebration" },
      { id: "overnight", label: "an overnight stay" },
      { id: "campus_hangout", label: "a campus hangout" },
      { id: "group_photo", label: "taking a group photo" },
      { id: "planning", label: "planning where to go" },
    ],
  },
  {
    id: "barkada_expect",
    category: "Barkada",
    hint: "Think about something that usually happens with friends.",
    text: "Thing you can almost always expect during {value}",
    options: [
      { id: "lunch", label: "barkada lunch" },
      { id: "study", label: "a study session" },
      { id: "outing", label: "an outing" },
      { id: "group_chat", label: "an active group chat" },
      { id: "birthday", label: "a birthday" },
      { id: "vacant", label: "a shared vacant" },
      { id: "commute", label: "a group commute" },
      { id: "coffee", label: "a coffee hangout" },
      { id: "project", label: "a friend-group project" },
      { id: "weekend", label: "a weekend meetup" },
    ],
  },
  {
    id: "barkada_role",
    category: "Barkada",
    hint: "Think about roles people naturally take in a friend group.",
    text: "Most useful role to have during {value}",
    options: [
      { id: "outing", label: "an outing" },
      { id: "planning", label: "planning a meetup" },
      { id: "study", label: "a study session" },
      { id: "group_order", label: "a group food order" },
      { id: "trip", label: "a trip" },
      { id: "birthday", label: "a birthday plan" },
      { id: "project", label: "a group project" },
      { id: "photo", label: "taking group photos" },
      { id: "commute", label: "traveling together" },
      { id: "event", label: "attending an event together" },
    ],
  },
  {
    id: "random_first",
    category: "Random",
    hint: "An everyday situation or habit.",
    text: "First thing you do when {value}",
    options: [
      { id: "battery5", label: "your battery hits 5%" },
      { id: "wifi_down", label: "the Wi-Fi goes down" },
      { id: "wake_early", label: "you wake up much earlier than expected" },
      { id: "rain", label: "it suddenly rains" },
      { id: "free_time", label: "you suddenly get free time" },
      { id: "hungry", label: "you realize you are very hungry" },
      { id: "lost_item", label: "you cannot find something important" },
      { id: "late", label: "you realize you are running late" },
      { id: "phone_freeze", label: "your phone freezes" },
      { id: "plans_cancel", label: "your plans get cancelled" },
    ],
  },
  {
    id: "random_annoying",
    category: "Random",
    hint: "Think about a common everyday annoyance.",
    text: "Most annoying thing when {value}",
    options: [
      { id: "battery_low", label: "your battery is low" },
      { id: "wifi_slow", label: "the Wi-Fi is slow" },
      { id: "raining", label: "it is raining" },
      { id: "hurry", label: "you are in a hurry" },
      { id: "sleepy", label: "you are sleepy" },
      { id: "hungry", label: "you are hungry" },
      { id: "waiting", label: "you have been waiting too long" },
      { id: "hot", label: "it is unexpectedly hot" },
      { id: "cold", label: "it is unexpectedly cold" },
      { id: "phone_storage", label: "your phone storage is full" },
    ],
  },
  {
    id: "random_check",
    category: "Random",
    hint: "Think about a normal habit before doing something.",
    text: "Something you always check before {value}",
    options: [
      { id: "leave_house", label: "leaving the house" },
      { id: "sleep", label: "going to sleep" },
      { id: "submit", label: "submitting something important" },
      { id: "travel", label: "going somewhere far" },
      { id: "class", label: "entering class" },
      { id: "buy", label: "buying something" },
      { id: "send", label: "sending an important message" },
      { id: "charge", label: "charging your phone" },
      { id: "meet", label: "meeting someone" },
      { id: "rain", label: "going outside when it might rain" },
    ],
  },
  {
    id: "random_best",
    category: "Random",
    hint: "Think about the upside of an everyday situation.",
    text: "Best thing about {value}",
    options: [
      { id: "free_weekend", label: "a completely free weekend" },
      { id: "cancelled_plan", label: "a cancelled plan" },
      { id: "early_finish", label: "finishing early" },
      { id: "rainy_day", label: "a rainy day" },
      { id: "quiet_day", label: "a quiet day" },
      { id: "no_alarm", label: "a morning with no alarm" },
      { id: "empty_schedule", label: "an empty schedule" },
      { id: "good_wifi", label: "really good Wi-Fi" },
      { id: "full_battery", label: "a fully charged phone" },
      { id: "good_sleep", label: "getting enough sleep" },
    ],
  },
  {
    id: "random_reason",
    category: "Random",
    hint: "Think about why someone might suddenly change what they are doing.",
    text: "Most likely reason you would suddenly {value}",
    options: [
      { id: "go_offline", label: "go offline" },
      { id: "leave_chat", label: "leave a chat" },
      { id: "change_plan", label: "change your plan" },
      { id: "take_nap", label: "take a nap" },
      { id: "buy_food", label: "buy food" },
      { id: "check_phone", label: "check your phone" },
      { id: "go_home", label: "go home early" },
      { id: "wear_jacket", label: "put on a jacket" },
      { id: "charge_phone", label: "charge your phone" },
      { id: "cancel", label: "cancel something" },
    ],
  },
  {
    id: "random_likely",
    category: "Random",
    hint: "Think about an everyday situation where something usually goes wrong.",
    text: "Most likely thing to happen when {value}",
    options: [
      { id: "hurry", label: "you are in a hurry" },
      { id: "late", label: "you are already late" },
      { id: "no_umbrella", label: "you forgot your umbrella" },
      { id: "low_battery", label: "your battery is almost dead" },
      { id: "no_data", label: "you have no mobile data" },
      { id: "very_sleepy", label: "you are extremely sleepy" },
      { id: "hungry", label: "you are very hungry" },
      { id: "need_focus", label: "you really need to focus" },
      { id: "saving_money", label: "you are trying to save money" },
      { id: "waiting_reply", label: "you are waiting for an important reply" },
    ],
  }
];

export const GENERATED_TOPICS: BluffTopic[] =
  TOPIC_TEMPLATES.flatMap(
    (template) =>
      template.options.map(
        (option) => ({
          id:
            `gen:${template.id}:${option.id}`,
          category:
            template.category,
          text:
            template.text.replace(
              '{value}',
              option.label
            ),
          hint:
            template.hint,
          source:
            'generated' as const,
        })
      )
  );

/*
 * This is the complete playable pool.
 * IDs are stable, so player history can remember exact prompts
 * across rooms, days, and weeks.
 */
export const TOPICS: BluffTopic[] = [
  ...CURATED_TOPICS,
  ...GENERATED_TOPICS,
];

export const getTopic = (
  topicId?: string | null
) =>
  TOPICS.find(
    (topic) =>
      topic.id === topicId
  ) ?? null;
