'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createTeamMember, updateTeamMember } from '../actions';
import { TeamRoleBadge } from '@/components/TeamRoleBadge';
import type { TeamRole, TeamStatus } from '@/lib/team/types';

export type ManagedMember = { uid: string; displayName: string; email: string; role: TeamRole; status: TeamStatus; lastLogin: string; activity: { reviewedPosts: number; approvedPosts: number; rejectedPosts: number; reportsResolved: number } };

export function MemberManager({ members }: { members: ManagedMember[] }) {
  const router = useRouter(); const [feedback, setFeedback] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); setFeedback(''); try { const result = await createTeamMember(new FormData(event.currentTarget)); if (result.success) { setFeedback('Team account created. Share the temporary password securely.'); event.currentTarget.reset(); router.refresh(); } else setError(result.error || 'Could not create account.'); } catch { setError('Could not create account.'); } finally { setBusy(false); } }
  async function update(uid: string, role: TeamRole, status: TeamStatus) { if (!confirm(`Apply ${role} / ${status} to this member?`)) return; setBusy(true); setError(''); const data = new FormData(); data.set('uid', uid); data.set('role', role); data.set('status', status); try { const result = await updateTeamMember(data); if (result.success) { setFeedback('Member access updated.'); router.refresh(); } else setError(result.error || 'Could not update access.'); } catch { setError('Could not update access.'); } finally { setBusy(false); } }
  return <div className="space-y-8">
    <section className="rounded-2xl border border-neutral-200 bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900"><h2 className="text-lg font-bold">Create team account</h2><p className="mt-1 text-sm text-neutral-500">Set a temporary password and share it securely with the member. It is sent directly to Firebase Authentication and is never stored in Firestore.</p><form onSubmit={create} className="mt-5 grid gap-4 md:grid-cols-2">
      <input name="displayName" required minLength={2} maxLength={50} placeholder="Display name" aria-label="Display name" className="rounded-xl border border-neutral-300 bg-transparent px-4 py-3 text-sm dark:border-neutral-700" /><input name="email" required type="email" placeholder="Email" aria-label="Email" className="rounded-xl border border-neutral-300 bg-transparent px-4 py-3 text-sm dark:border-neutral-700" /><input name="temporaryPassword" required type="password" minLength={12} autoComplete="new-password" placeholder="Temporary password (12+ characters)" aria-label="Temporary password" className="rounded-xl border border-neutral-300 bg-transparent px-4 py-3 text-sm dark:border-neutral-700" /><select name="role" aria-label="Role" className="rounded-xl border border-neutral-300 bg-transparent px-4 py-3 text-sm dark:border-neutral-700 dark:bg-neutral-900"><option value="admin">Admin</option><option value="moderator">Moderator</option><option value="marketing">Marketing</option></select><button disabled={busy} className="rounded-xl bg-neutral-950 px-5 py-3 font-mono text-xs font-bold uppercase text-white disabled:opacity-50 dark:bg-white dark:text-neutral-950 md:col-span-2">Create account</button>
    </form>{feedback && <p role="status" className="mt-4 text-sm text-emerald-600">{feedback}</p>}{error && <p role="alert" className="mt-4 text-sm text-rose-600">{error}</p>}</section>
    <section><h2 className="text-lg font-bold">Team members</h2><div className="mt-4 space-y-3">{members.map((member) => <MemberRow key={member.uid} member={member} busy={busy} update={update} />)}{!members.length && <p className="rounded-xl border border-neutral-200 p-8 text-center text-sm text-neutral-500">No team members found.</p>}</div></section>
  </div>;
}

function MemberRow({ member, busy, update }: { member: ManagedMember; busy: boolean; update: (uid: string, role: TeamRole, status: TeamStatus) => void }) {
  const [role, setRole] = useState(member.role); const [status, setStatus] = useState(member.status); const locked = member.role === 'owner';
  return <article className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong>{member.displayName}</strong><TeamRoleBadge role={member.role} /><span className="font-mono text-[9px] uppercase text-neutral-500">{member.status}</span></div><p className="mt-1 text-sm text-neutral-500">{member.email} · Last login: {member.lastLogin}</p><p className="mt-2 font-mono text-[10px] text-neutral-400">Reviewed {member.activity.reviewedPosts} · Approved {member.activity.approvedPosts} · Rejected {member.activity.rejectedPosts} · Reports {member.activity.reportsResolved}</p></div>{!locked && member.status !== 'revoked' && <div className="flex flex-wrap gap-2"><select value={role} onChange={(e) => setRole(e.target.value as TeamRole)} className="rounded-lg border border-neutral-300 bg-transparent px-3 py-2 text-xs dark:border-neutral-700 dark:bg-neutral-900"><option value="admin">Admin</option><option value="moderator">Moderator</option><option value="marketing">Marketing</option></select><select value={status} onChange={(e) => setStatus(e.target.value as TeamStatus)} className="rounded-lg border border-neutral-300 bg-transparent px-3 py-2 text-xs dark:border-neutral-700 dark:bg-neutral-900"><option value="active">Active</option><option value="suspended">Suspended</option><option value="revoked">Revoke access</option></select><button disabled={busy || (role === member.role && status === member.status)} onClick={() => update(member.uid, role, status)} className="rounded-lg bg-neutral-900 px-4 py-2 font-mono text-[10px] font-bold uppercase text-white disabled:opacity-40 dark:bg-white dark:text-neutral-900">Apply</button></div>}</div></article>;
}
