'use client';

import { FormEvent, useDeferredValue, useState } from 'react';
import { useRouter } from 'next/navigation';
import { approvePendingPost, escalateReport, rejectPendingPost, resolveContentReport } from '../moderation-actions';

export type PendingItem = { id: string; content: string; category: string; createdAt: string; imageUrl?: string };
export type ReportItem = { id: string; postId: string; replyId?: string; contentType: 'post' | 'reply'; reason: string; details: string; content: string; createdAt: string; escalated: boolean };
export type HistoryItem = { id: string; action: string; moderator: string; date: string; reason?: string; summary?: string };

export function ModerationWorkspace({ pending, reports, history, stats, canResolveSensitive }: { pending: PendingItem[]; reports: ReportItem[]; history: HistoryItem[]; stats: Record<string, number>; canResolveSensitive: boolean }) {
  const router = useRouter(); const [tab, setTab] = useState<'pending'|'reports'|'history'|'guidelines'>('pending'); const [search, setSearch] = useState(''); const deferredSearch = useDeferredValue(search.toLowerCase()); const [feedback, setFeedback] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const run = async (key: string, action: () => Promise<{ success: boolean; error?: string }>) => { setBusy(key); setError(''); setFeedback(''); try { const result = await action(); if (result.success) { setFeedback('Moderation decision recorded.'); router.refresh(); } else setError(result.error || 'Action failed.'); } catch { setError('Action failed. Please refresh and try again.'); } finally { setBusy(''); } };
  const pendingFiltered = pending.filter((item) => `${item.content} ${item.category}`.toLowerCase().includes(deferredSearch)); const reportsFiltered = reports.filter((item) => `${item.content} ${item.reason} ${item.details}`.toLowerCase().includes(deferredSearch));
  return <div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Reviewed',stats.reviewedPosts],['Approved',stats.approvedPosts],['Rejected',stats.rejectedPosts],['Reports resolved',stats.reportsResolved]].map(([label,value]) => <div key={String(label)} className="rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900"><p className="font-mono text-[9px] uppercase tracking-wider text-neutral-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div>
    <div className="mt-8 flex gap-2 overflow-x-auto border-b border-neutral-200 dark:border-neutral-800">{(['pending','reports','history','guidelines'] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap border-b-2 px-3 py-3 font-mono text-[10px] font-bold uppercase tracking-wider ${tab === item ? 'border-emerald-500 text-emerald-700 dark:text-emerald-400' : 'border-transparent text-neutral-500'}`}>{item}</button>)}</div>
    {(tab === 'pending' || tab === 'reports') && <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search content, category, or reason..." className="mt-5 w-full rounded-xl border border-neutral-300 bg-white px-4 py-3 text-sm dark:border-neutral-700 dark:bg-neutral-900" />}
    {feedback && <p role="status" className="mt-4 rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">{feedback}</p>}{error && <p role="alert" className="mt-4 rounded-lg bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">{error}</p>}
    {tab === 'pending' && <div className="mt-5 space-y-4">{pendingFiltered.map((item) => <PendingCard key={item.id} item={item} busy={busy} run={run} />)}{!pendingFiltered.length && <Empty text="No pending posts match this view." />}</div>}
    {tab === 'reports' && <div className="mt-5 space-y-4">{reportsFiltered.map((item) => <ReportCard key={item.id} item={item} busy={busy} canResolveSensitive={canResolveSensitive} run={run} />)}{!reportsFiltered.length && <Empty text="No content reports match this view." />}</div>}
    {tab === 'history' && <div className="mt-5 space-y-3">{history.map((item) => <article key={item.id} className="rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{item.action.replaceAll('_',' ')}</strong><time className="font-mono text-[10px] text-neutral-400">{item.date}</time></div><p className="mt-1 text-xs text-neutral-500">By {item.moderator}{item.reason ? ` · ${item.reason}` : ''}</p>{item.summary && <p className="mt-2 line-clamp-2 text-sm text-neutral-600 dark:text-neutral-300">{item.summary}</p>}</article>)}{!history.length && <Empty text="No moderation decisions have been recorded yet." />}</div>}
    {tab === 'guidelines' && <Guidelines />}
  </div>;
}

function PendingCard({ item, busy, run }: { item: PendingItem; busy: string; run: Function }) { const [content,setContent]=useState(item.content); const [reason,setReason]=useState(''); return <article className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex flex-wrap justify-between gap-2"><span className="rounded-full bg-neutral-100 px-2 py-1 font-mono text-[9px] uppercase dark:bg-neutral-800">{item.category}</span><time className="font-mono text-[10px] text-neutral-400">{item.createdAt}</time></div><textarea value={content} onChange={(e)=>setContent(e.target.value)} className="mt-4 min-h-32 w-full rounded-xl border border-neutral-200 bg-neutral-50 p-4 text-sm leading-6 dark:border-neutral-700 dark:bg-neutral-950" />{item.imageUrl && <img src={item.imageUrl} alt="Pending post attachment" className="mt-3 max-h-72 rounded-xl object-contain" />}<input value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Optional rejection reason" className="mt-3 w-full rounded-lg border border-neutral-200 bg-transparent px-3 py-2 text-sm dark:border-neutral-700" /><div className="mt-4 flex justify-end gap-2"><button disabled={!!busy} onClick={()=>{if(confirm('Reject and permanently remove this pending post?')){const data=new FormData();data.set('postId',item.id);data.set('reason',reason);run(item.id,()=>rejectPendingPost(data));}}} className="rounded-lg border border-rose-300 px-4 py-2 text-xs font-bold text-rose-700 disabled:opacity-50">Reject</button><button disabled={!!busy} onClick={()=>{if(confirm('Approve this post for the public Freedom Wall?')){const data=new FormData();data.set('postId',item.id);data.set('content',content);run(item.id,()=>approvePendingPost(data));}}} className="rounded-lg bg-emerald-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Approve</button></div></article>; }
function ReportCard({ item,busy,canResolveSensitive,run }:{item:ReportItem;busy:string;canResolveSensitive:boolean;run:Function}) { const sensitive=/doxx|personal info|allegation|threat|self-harm|minor/i.test(`${item.reason} ${item.details} ${item.content}`); const adminRequired=!canResolveSensitive&&(sensitive||item.escalated); return <article className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-rose-50 px-2 py-1 font-mono text-[9px] font-bold uppercase text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">{item.contentType}</span><strong className="text-sm">{item.reason}</strong>{item.escalated && <span className="rounded-full bg-amber-100 px-2 py-1 font-mono text-[9px] uppercase text-amber-800">Escalated</span>}<time className="ml-auto font-mono text-[10px] text-neutral-400">{item.createdAt}</time></div><p className="mt-4 whitespace-pre-wrap rounded-xl bg-neutral-50 p-4 text-sm leading-6 dark:bg-neutral-950">{item.content || '[Content unavailable]'}</p>{item.details && <p className="mt-2 text-xs text-neutral-500">Reporter notes: {item.details}</p>}<div className="mt-4 flex flex-wrap justify-end gap-2">{adminRequired ? (item.escalated ? <span className="rounded-lg bg-amber-50 px-4 py-2 text-xs font-semibold text-amber-800 dark:bg-amber-950/40 dark:text-amber-300">Awaiting Admin review</span> : <button disabled={!!busy} onClick={()=>{const data=new FormData();data.set('reportId',item.id);data.set('note','Sensitive content requires Admin review');run(item.id,()=>escalateReport(data));}} className="rounded-lg bg-amber-500 px-4 py-2 text-xs font-bold text-neutral-950">Escalate to Admin</button>) : <><button disabled={!!busy} onClick={()=>{if(confirm('Dismiss this report and keep the content?')){const data=new FormData();data.set('reportId',item.id);data.set('decision','dismiss');run(item.id,()=>resolveContentReport(data));}}} className="rounded-lg border border-neutral-300 px-4 py-2 text-xs font-bold">Dismiss</button><button disabled={!!busy} onClick={()=>{if(confirm(`Permanently remove this ${item.contentType}?`)){const data=new FormData();data.set('reportId',item.id);data.set('decision','remove');run(item.id,()=>resolveContentReport(data));}}} className="rounded-lg bg-rose-600 px-4 py-2 text-xs font-bold text-white">Remove content</button></>}</div></article>; }
function Empty({text}:{text:string}) { return <p className="rounded-xl border border-dashed border-neutral-300 px-4 py-12 text-center text-sm text-neutral-500 dark:border-neutral-700">{text}</p>; }
function Guidelines(){return <section className="mt-5 rounded-2xl border border-neutral-200 bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900"><h2 className="text-lg font-bold">Moderation guidelines</h2><div className="mt-5 space-y-5 text-sm leading-6 text-neutral-600 dark:text-neutral-300"><p><strong className="text-neutral-900 dark:text-white">Privacy and doxxing.</strong> Remove phone numbers, addresses, account credentials, schedules, or identifying details that could put someone at risk. Escalate credible threats and sensitive allegations.</p><p><strong className="text-neutral-900 dark:text-white">Harassment.</strong> Distinguish criticism from targeted abuse, threats, repeated humiliation, and calls for harassment.</p><p><strong className="text-neutral-900 dark:text-white">Sensitive allegations.</strong> Do not investigate or expose identities. Preserve only the minimum necessary information and escalate to an Admin.</p><p><strong className="text-neutral-900 dark:text-white">Consistency.</strong> Judge the content against the public TambayanSLU community guidelines, not personal agreement with the opinion.</p><a href="/guidelines" target="_blank" className="inline-block font-semibold text-emerald-700 underline dark:text-emerald-400">Open full community guidelines</a></div></section>;}
